# Generated by Django 5.0.4 on 2024-05-05 19:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Talks', '0005_alter_talk_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Talk',
            new_name='Talks',
        ),
    ]
